# Cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cleks-cluster
  region: ap-northeast-2
  
vpc:
  subnets:
    public: 
      ap-northeast-2a: {id: <public_subnet_id>}
      ap-northeast-2b: {id: <public_subnet_id>}
    private:
      ap-northeast-2a: {id: <private_subnet_id>}
      ap-northeast-2b: {id: <private_subnet_id>}


nodeGroups:
  - name: cleks-ng
    labels: {role: worker}
    instanceType: t3.large
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 50
    ssh:
      publicKeyName: <keypair_name>

# eksctl create cluster -f Cluster.yaml